### ISSUE TITLE
依赖模块冲突

### ISSUE THREAD

**Issue by wenhuiwwh** [logan-zou/Chat_with_Datawhale_langchain#10]
ERROR: Cannot install -r requirements.txt (line 4), -r requirements.txt (line 40), -r requirements.txt (line 41), -r requirements.txt (line 48), -r requirements.txt (line 53), -r requirements.txt (line 74), -r requirements.txt (line 75), -r requirements.txt (line 87), langchain and packaging==23.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested packaging==23.1
    altair 5.1.2 depends on packaging
    gradio 3.40.1 depends on packaging
    gradio-client 0.7.0 depends on packaging
    huggingface-hub 0.17.3 depends on packaging>=20.9
    ipykernel 6.23.1 depends on packaging
    marshmallow 3.20.1 depends on packaging>=17.0
    matplotlib 3.8.1 depends on packaging>=20.0
    onnxruntime 1.16.2 depends on packaging
    langchain-core 0.2.43 depends on packaging<25 and >=23.2
    The user requested packaging==23.1
    altair 5.1.2 depends on packaging
    gradio 3.40.1 depends on packaging
    gradio-client 0.7.0 depends on packaging
    huggingface-hub 0.17.3 depends on packaging>=20.9
    ipykernel 6.23.1 depends on packaging
    marshmallow 3.20.1 depends on packaging>=17.0
    matplotlib 3.8.1 depends on packaging>=20.0
    onnxruntime 1.16.2 depends on packaging
    langchain-core 0.2.42 depends on packaging<25 and >=23.2
    The user requested packaging==23.1
    altair 5.1.2 depends on packaging
    gradio 3.40.1 depends on packaging
    gradio-client 0.7.0 depends on packaging
    huggingface-hub 0.17.3 depends on packaging>=20.9
    ipykernel 6.23.1 depends on packaging
    marshmallow 3.20.1 depends on packaging>=17.0
    matplotlib 3.8.1 depends on packaging>=20.0
    onnxruntime 1.16.2 depends on packaging
    langchain-core 0.2.41 depends on packaging<25 and >=23.2
    The user requested packaging==23.1
    altair 5.1.2 depends on packaging
    gradio 3.40.1 depends on packaging
    gradio-client 0.7.0 depends on packaging
    huggingface-hub 0.17.3 depends on packaging>=20.9
    ipykernel 6.23.1 depends on packaging
    marshmallow 3.20.1 depends on packaging>=17.0
    matplotlib 3.8.1 depends on packaging>=20.0
    onnxruntime 1.16.2 depends on packaging
    langchain-core 0.2.40 depends on packaging<25 and >=23.2
    The user requested packaging==23.1
    altair 5.1.2 depends on packaging
    gradio 3.40.1 depends on packaging
    gradio-client 0.7.0 depends on packaging
    huggingface-hub 0.17.3 depends on packaging>=20.9
    ipykernel 6.23.1 depends on packaging
    marshmallow 3.20.1 depends on packaging>=17.0
    matplotlib 3.8.1 depends on packaging>=20.0
    onnxruntime 1.16.2 depends on packaging
    langchain-core 0.2.39 depends on packaging<25 and >=23.2
    The user requested packaging==23.1
    altair 5.1.2 depends on packaging
    gradio 3.40.1 depends on packaging
    gradio-client 0.7.0 depends on packaging
    huggingface-hub 0.17.3 depends on packaging>=20.9
    ipykernel 6.23.1 depends on packaging
    marshmallow 3.20.1 depends on packaging>=17.0
    matplotlib 3.8.1 depends on packaging>=20.0
    onnxruntime 1.16.2 depends on packaging
    langchain-core 0.2.38 depends on packaging<25 and >=23.2
pip安装requirements.txt提示好多模块冲突，请楼主核查一下模块包版本

**Comment by lta155** [comment]
不好意思最近没太有时间 刚看到您这边issue 依赖冲突可以参考之前一位小伙伴的[方案](https://zhuanlan.zhihu.com/p/694891334?utm_campaign=shareopn&utm_medium=social&utm_psn=1767796448706560000&utm_source=wechat_session)解决

**Comment by alvin-susu** [comment]
这项目的第一步就把人劝退了

**Comment by CaiY980** [comment]
> 不好意思最近没太有时间 刚看到您这边issue 依赖冲突可以参考之前一位小伙伴的[方案](https://zhuanlan.zhihu.com/p/694891334?utm_campaign=shareopn&utm_medium=social&utm_psn=1767796448706560000&utm_source=wechat_session)解决

除了按照上述的方法，还需要把python版本设置为3.11.0 才没有冲突

**Comment by luhterluo** [comment]
Ubuntu 安装，python 3.10 , 使用虚拟全新环境， 安装基础包就出错。 
Traceback (most recent call last):
  File "/root/aiapp/Chat_with_Datawhale_langchain/serve/api.py", line 13, in <module>
    from fastapi import FastAPI
  File "/root/aiapp/Chat_with_Datawhale_langchain/venv_local/lib/python3.10/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/root/aiapp/Chat_with_Datawhale_langchain/venv_local/lib/python3.10/site-packages/fastapi/applications.py", line 15, in <module>
    from fastapi import routing
  File "/root/aiapp/Chat_with_Datawhale_langchain/venv_local/lib/python3.10/site-packages/fastapi/routing.py", line 21, in <module>
    from fastapi import params
  File "/root/aiapp/Chat_with_Datawhale_langchain/venv_local/lib/python3.10/site-packages/fastapi/params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (/root/aiapp/Chat_with_Datawhale_langchain/venv_local/lib/python3.10/site-packages/pydantic/fields.py)

**Comment by FengFeng-huang** [comment]
python版本设置为3.11.0，并且requirements.txt中去掉所有版本信息，即可正常安装。
