### ISSUE TITLE
是否支持Windows系统？

### ISSUE THREAD

**Issue by TonyWang972** [logan-zou/Chat_with_Datawhale_langchain#2]
使用windows系统进行pip安装包时会报以下的错误，似乎是uvloop这个包不支持Windows系统，与文档中系统匹配描述不一致
`  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Lenovo\.conda\envs\llm-universe\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Lenovo\.conda\envs\llm-universe\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Lenovo\.conda\envs\llm-universe\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-1b50t8y6\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-1b50t8y6\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Lenovo\AppData\Local\Temp\pip-build-env-1b50t8y6\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]`

**Comment by SeanFeng91** [comment]
卡在这里了，遇到了同样的问题，前面应该还有一个wheel问题。然后跳过这里运行api还提示ModuleNotFoundError: No module named 'fastapi'

**Comment by BenWyy** [comment]
windows系统没有uvloop这个包的，可以尝试在requirements.txt删除这个包。
linux系统也有问题，requirements.txt给出的langchain相关的依赖版本似乎不正确，无法编译成功。

**Comment by maoyaozong** [comment]
有跑成功的同学吗

**Comment by alvin-susu** [comment]
没有跑成功过

**Comment by sevenboom** [comment]
我让Gemini帮我分析整个项目的依赖帮我生成了一个requirements.txt。内容如下：
``` requiresments.txt
# Basics
python-dotenv==1.0.0
requests==2.31.0
tqdm==4.66.1

# Web Framework / Interface
fastapi==0.85.1
uvicorn==0.24.0.post1
gradio==3.40.1

# LLM & AI
openai==0.27.6
zhipuai==1.0.7
langchain==0.0.292
websocket-client==1.5.2

# Vector Database
chromadb==0.3.29

# Document Processing
PyMuPDF==1.23.6
unstructured==0.9.0
markdown

# Utilities
pydantic==1.10.10
ipython==8.12.3
scikit-learn==1.2.2
numpy==1.26.2

```
在windows下还是按照README.md中的方式新建conda环境，安装依赖包。
然后参考这个其他issue中给的[链接教程](https://zhuanlan.zhihu.com/p/694891334?utm_campaign=shareopn&utm_medium=social&utm_psn=1767796448706560000&utm_source=wechat_session)修改一些环境配置，确实可以跑起来了
